(function(){'use strict';var base=ViewControllerManager.findClass('ViewControllerNav');ViewControllerManager.newClassDef('PlayerVC',Class.create({_extends_:base,_init_:function(args){base.call(this,args);this.activeChild='playPause';this.navigation={'rewind':{Right:'playPause'},'playPause':{Left:'rewind',Right:'forward'},'forward':{Left:'playPause',Right:'CC'},'CC':{Left:'forward'}};this.scrubAmount=1;this.scrubTimeout=null;this.scrubTime=0;this.defaultScrubSpeeds=[{speed:500,label:'x2',scrubAmount:1},{speed:250,label:'x4',scrubAmount:1},{speed:125,label:'x8',scrubAmount:1},{speed:62,label:'x16',scrubAmount:1},{speed:31,label:'x32',scrubAmount:1},{speed:31,label:'x64',scrubAmount:2},{speed:31,label:'x128',scrubAmount:4}];this.panasonicScrubSpeeds=[{speed:1000,label:'x2',scrubAmount:2},{speed:1000,label:'x4',scrubAmount:4},{speed:1000,label:'x8',scrubAmount:8},{speed:1000,label:'x16',scrubAmount:16},{speed:1000,label:'x32',scrubAmount:32},{speed:1000,label:'x64',scrubAmount:64},{speed:1000,label:'x128',scrubAmount:128}];this.scrubSpeeds=(settings.device==='panasonic')?this.panasonicScrubSpeeds:this.defaultScrubSpeeds;this.scrubSpeedIndex=0;this.scrubDirection=0;this.previewImages=[];this.thumbElements=[];this.subTitles=[];this.captionIndex=0;this.captions=false;this.captionsIndex=0;this.findCaption=false;this.waitToShowResume=false;this.checkSeek=false;this.deferredResume=false;this.deferredSeek=false;this.stopPlayer=true;this.playerError=false;this.simulateBufferProgress=0;this.playerLangOptions=false;},onUnload:function(){},onLoad:function(){},render:function(location){this._super(location);this.enable();this._showPlayer();if(Model.App.trailer){this._watchTrailer();}else if(Model.App.AmazonIAP){this._amazonWatchMovie();}
else{Util.showSpriteLoader();this._watchMovie();}},_watchMovie:function(){var scope=this;var home=ViewControllerManager.find('Home');API.watchMovie(Model.App.movie.flix_id,function(res){Util.hideSpriteLoader();scope.passId=res.pass.id;scope.userLeftReview=res.member_has_left_review;Model.App.seekTime=0;Model.App.movie.url=res.url;if(settings.device==='chrome'){VideoController.setURL('http://p.demo.flowplayer.netdna-cdn.com/vod/demo.flowplayer/bbb-800.mp4');}else{VideoController.setURL(Model.App.movie.url);}
if(Model.App.movie.subtitles&&Model.App.movie.subtitles.length>0){scope.SubtitleOptions=Model.App.movie.subtitles;scope.getSubtitles(Model.App.movie.subtitles[scope.captionsIndex]);scope._showCCButton();}else{scope._hideCCButton();}
if(res.seek_time>0&&res.seek_time<Model.App.movie.duration_seconds-20){scope.waitToShowResume=true;Model.App.seekTime=res.seek_time;scope.publish('ResumeMovie');}else{scope.playPause();}
scope._setTizenResume();},function(res,errorCode){Model.App.errorCode=errorCode;home.publish('Error');});},_watchTrailer:function(){TVA.log(Model.App.movie.imagery.trailers[0].url);var temp_url=Model.App.movie.imagery.trailers[0].url;VideoController.setURL(temp_url);this._hideCCButton();this.playPause();},_amazonWatchMovie:function(){Model.App.AmazonIAP=false;if(settings.device==='chrome'){VideoController.setURL('http://p.demo.flowplayer.netdna-cdn.com/vod/demo.flowplayer/bbb-800.mp4');}else{VideoController.setURL(Model.App.movie.url);}
if(Model.App.movie.subtitles&&Model.App.movie.subtitles.length>0){this.SubtitleOptions=Model.App.movie.subtitles;this.getSubtitles(Model.App.movie.subtitles[this.captionsIndex]);this._showCCButton();}else{this._hideCCButton();}
if(Model.App.seek_time>0&&Model.App.seek_time<Model.App.movie.duration_seconds-20){this.waitToShowResume=true;this.publish('ResumeMovie');}else{this.playPause();}},playPause:function(seekTime){this._lockRootVC(true);if(this.scrubbing){this._seekResume();}
else if(VideoController.buffering&&settings.device==='panasonic'){this._resume();}
else if(VideoController.paused){this._resume();}else if(VideoController.playing){this._pause();}else{if(seekTime)
this._play(seekTime);else
this._play();}
TVA.setFocus('playPause');this.activeChild='playPause';this._lockRootVC(false);},playHead:function(seconds){var scope=this;var progress=(seconds/this.movieLength)*100;this._fakeBufferingProgress(progress);this._updatePlayerTime('current',seconds);this._updatePlayerTime('total',VideoController.getLength());this._progressBar(progress);if(this.captions){this.runSubtitles(seconds,this.findCaption);}
if(seconds!==0&&seconds%10===0&&!Model.App.trailer&&!this.scrubbing&&this.currentSeconds!==seconds){API.updateSeek({seek_time:seconds,duration:scope.movieLength===Infinity?0:scope.movieLength,id:scope.passId},function(a){},function(a,errorCode){TVA.log(a.errorThrown.responseText);Model.App.errorCode=errorCode;scope.publish("Error");});}
if(scope.waitToShowResume){scope.waitToShowResume=false;if(settings.device!=='samsung_tizen'){VideoController.forward(Model.App.seekTime);}
scope.checkSeek=true;}
if(scope.checkSeek&&settings.device==='samsung_tizen'){if(!VideoController.connecting&&!VideoController.buffering){scope.checkSeek=false;scope.deferredResume=true;VideoController.pause(true);}}
this.currentSeconds=seconds;},stateChange:function(state){var scope=this;this.playerError=false;switch(state){case 1:Util.showSpriteLoader();scope.movieLength=VideoController.getLength();TVA.log('MovieLength '+scope.movieLength);this._updatePlayerTime('total',scope.movieLength);this._toggleClass('#playPause','paused','playing');break;case 2:this._toggleClass('#playPause','playing','paused');Util.hideSpriteLoader();var fakeBufferValue=scope.simulateBufferProgress+1;scope._fakeBufferingProgress(fakeBufferValue);if(scope.deferredSeek){scope.deferredSeek=false;scope._resume();}
if(scope.deferredResume){VideoController.forward(Model.App.seekTime);scope.deferredResume=false;scope.deferredSeek=true;}
break;case 3:case 4:if(settings.device==='operatv'||settings.device==='panasonic'){if(!this.playerError&&(!ViewControllerManager.ViewControllers.Modal.children.ModalResume&&ViewControllerManager.ViewControllers.Home.activeChild!=='Details')){TVA.log('LOADING...');Util.showSpriteLoader();}}else{Util.showSpriteLoader();}
break;case 5:this.stopPlayer=false;if(!ViewControllerManager.ViewControllers.Modal.children.ModalRating&&(ViewControllerManager.ViewControllers.Root.activeChild==='Player'||ViewControllerManager.ViewControllers.Home.activeChild!=='Details')){console.log("---  Back on finished.");scope.back();}
Util.hideSpriteLoader();break;case 6:this.playerError=true;this.stopPlayer=settings.device==='panasonic';if(!ViewControllerManager.ViewControllers.Modal.children.ModalRating&&ViewControllerManager.ViewControllers.Home.activeChild!=='Details'&&ViewControllerManager.ViewControllers.Home.activeChild!=='mainMenu'&&ViewControllerManager.ViewControllers.Home.activeChild!=='categoriesList'){console.log("---  Back on error.");scope.back();}
Util.hideSpriteLoader();break;}},_play:function(seektime){this._lockRootVC(true);VideoController.play(seektime);this._lockRootVC(false);},_pause:function(){this._lockRootVC(true);this._stopScrub();VideoController.pause();this._lockRootVC(false);},_stop:function(){this._lockRootVC(true);if(this.scrubbing)
this._stopScrub();if(this.stopPlayer){VideoController.stop();}
this._lockRootVC(false);},_seek:function(){this._stopScrub();var diff=this._getDiff();if(diff>1){TVA.log('SEEK FORWARD '+diff);VideoController.forward(diff);}
else{TVA.log('SEEK BACKWARDS '+diff);VideoController.backward(Math.abs(diff));}},_seekResume:function(){this._seek();this._resume();},_forward:function(){this._lockRootVC(true);this._toggleClass('#playSpeedBox .arrows','backward','forward');this._setScrub(1);this._lockRootVC(false);this.activeChild='forward';TVA.setFocus(this.activeChild);},_backward:function(){this._lockRootVC(true);this._toggleClass('#playSpeedBox .arrows','forward','backward');this._setScrub(-1);this._lockRootVC(false);this.activeChild='rewind';TVA.setFocus(this.activeChild);},_resume:function(){this._lockRootVC(true);VideoController.resume();this._lockRootVC(false);},_setTizenResume:function(){var scope=this;var home=ViewControllerManager.find('Home');TVA_Player.beforeRestoreCallback=function(call){Util.showSpriteLoader();API.watchMovie(Model.App.movie.flix_id,function(res){Util.hideSpriteLoader();scope.passId=res.pass.id;scope.userLeftReview=res.member_has_left_review;Model.App.seekTime=0;Model.App.movie.url=res.url;if(settings.device==='chrome'){VideoController.setURL('http://p.demo.flowplayer.netdna-cdn.com/vod/demo.flowplayer/bbb-800.mp4');}else{VideoController.setURL(Model.App.movie.url);}
call&&call();},function(res,errorCode){Model.App.errorCode=errorCode;home.publish('Error');});};},_showPlayer:function(){$('#splash-background').hide();$('#playerFooter').find('#back').text(language[Model.App.file.language].common.btn_back);this._hideCCButton();VideoController.showPlayer();this._showPlayerControls();$('#errorMsg').hide();$('#playSpeedBox').hide();$('#main-background').hide();},_hidePlayer:function(){var root=ViewControllerManager.find('Root');this._resetPlayer();VideoController.hidePlayer();root.removeChild('Player');root.children['Home'].view.enable();$('#AppContent').show();$('#main-background').show();},_showPlayerControls:function(){if(!this.disabled){$('#PlayerControls').css({'transition-duration':'1s'});$('#PlayerControls').css({bottom:0});this.listen=true;var scope=this;clearTimeout(scope.timeout);scope.timeout=setTimeout(function(){scope._hidePlayerControls();},3000);}},_hidePlayerControls:function(){var scope=this;var height=$('#PlayerControls').css('height');if(!VideoController.stopped&&!VideoController.paused&&VideoController.currentSeconds>3){$('#PlayerControls').css({'transition-duration':'2s'});$('#PlayerControls').css({bottom:('-'+height)});this.listen=false;}else{clearTimeout(scope.timeout);scope.timeout=setTimeout(function(){scope._hidePlayerControls(true);},3000);}},_disablePlayerControls:function(){this.disabled=true;this._hidePlayerControls();},_enablePlayerControls:function(){this.disabled=false;this._showPlayerControls();},_showCCButton:function(){$('#CC').show();this.navigation.forward.Right='CC';},_hideCCButton:function(){$('#CC').hide();this.navigation.forward={Left:'playPause'};},_updatePlayerTime:function(str,secs){if(str==='current'){$('#time').find('span:nth-child(1)').html(Util.secondsToTime(secs));}
else if(str==='total'){$('#time').find('span:nth-child(2)').html(Util.secondsToTime(secs));}
else{$('#time').find('span:nth-child(1)').html(Util.secondsToTime());$('#time').find('span:nth-child(2)').html(Util.secondsToTime());}},_resetPlayer:function(){this.subTitles=[];this.captionIndex=0;this.captions=false;this.captionsIndex=0;this.findCaption=false;this.waitToShowResume=false;this.checkSeek=false;this.deferredResume=false;this.deferredSeek=false;this.stopPlayer=true;this.playerError=false;this.currentSeconds=0;this.movieLength=0;this.simulateBufferProgress=0;this.playerLangOptions=false;this._bufferBar();this._progressBar();this._updatePlayerTime();TVA.log('TVA_Player reset');},onMouseLeave:function(e){$('#'+e.target.id).removeClass('active');},onBackHover:function(e){$('#'+e.target.id).addClass('active');},onHover:function(e){var element=e.target.id;this._enableElement(element);this._showPlayerControls();},onKeyDown:function(e,keyCode){console.log("---  Captured keydown on PlayerVC");if(ViewControllerManager.find('Root').locked){e.stopPropagation();return true;}
if(Model.App.listen&&this.listen){$('.hoveritemBack').removeClass('active');switch(keyCode){case Keys.getBind('QMENU'):VideoController.showQmenu();break;case Keys.getBind('Circle'):case Keys.getBind('Back'):this.back();e.stopImmediatePropagation();e.stopPropagation();break;case Keys.getBind('Up'):this._navigate('Up',e);e.stopPropagation();break;case Keys.getBind('Down'):this._navigate('Down',e);this.hideLangOptions();e.stopPropagation();break;case Keys.getBind('Left'):this._navigate('Left',e);e.stopPropagation();break;case Keys.getBind('Right'):this._navigate('Right',e);e.stopPropagation();break;case Keys.getBind('Play'):if(this.playerLangOptions)
this.hideLangOptions();this.playPause();break;case Keys.getBind('Stop'):console.log("---  Back on stop.");this.back();break;case Keys.getBind('Pause'):if(this.playerLangOptions)
this.hideLangOptions();this.playPause();break;case Keys.getBind('FF'):if(this.playerLangOptions)
this.hideLangOptions();this._forward();break;case Keys.getBind('RW'):if(this.playerLangOptions)
this.hideLangOptions();this._backward();break;case Keys.getBind('Cross'):case Keys.getBind('Enter'):$('#'+TVA.onFocus).click();e.stopImmediatePropagation();break;}}
e.stopPropagation();this._showPlayerControls();},back:function(){if(!VideoController.paused){VideoController.pause();}
this._stop();$(this.rootID+' .active').removeClass('active');$('#splash-background').show();Model.App.captionsIndex=null;this.captions=false;this.clearCaptions();var currentSeconds=VideoController.currentSeconds;var home=ViewControllerManager.find('Home');var details=ViewControllerManager.find('Details');if(Model.App.loggedIn&&!Model.App.trailer){home.removeChild('Details');home.addChild(details,'#screens');}
this._hidePlayer();if(!this.userLeftReview&&!Model.App.trailer&&(currentSeconds/Model.App.movie.duration_seconds>0.9)){Model.App.promptReview=true;}},_setScrub:function(direction){this._lockRootVC(true);if(direction!==this.scrubDirection){this.scrubDirection=direction;this.scrubSpeedIndex=0;}
this.scrubbing=true;VideoController.pause();var currentSeconds=VideoController.currentSeconds;clearTimeout(this.scrubTimeout);this.scrubDirection=direction;$('#playSpeedBox').show();$('#playSpeed').html(this.scrubSpeeds[this.scrubSpeedIndex].label);this.timeSlice=this.movieLength/this.previewImages.length;var scrubDirection=direction;var scrubSpeed=this.scrubSpeeds[this.scrubSpeedIndex].speed;var scrubLabel=this.scrubSpeeds[this.scrubSpeedIndex].label;var scrubAmount=this.scrubSpeeds[this.scrubSpeedIndex].scrubAmount;var scrubIncrement=scrubAmount*scrubDirection;this._scrub(scrubIncrement,currentSeconds,scrubSpeed,scrubLabel);this.scrubSpeedIndex++;if(this.scrubSpeedIndex===this.scrubSpeeds.length){this.scrubSpeedIndex=0;}
this._lockRootVC(false);},_scrub:function(scrubIncrement,start,scrubSpeed,label,prevIndex){var scope=this;var time=start+scrubIncrement;this.scrubTime=time;if(VideoController.playing){VideoController.pause();}
clearTimeout(this.scrubTimeout);if(prevIndex&&settings.device!=='panasonic'){$(this.thumbElements[prevIndex]).hide();}
if(time<=this.movieLength){if(time>=0){playHeadChanged(time);var index=Math.ceil(time/this.timeSlice);if(settings.device!=='panasonic'){$(this.thumbElements[index]).show();}}else{this._seekResume();}}else if(this.movieLength>0){this._stop();this.back();}
$('#playSpeed').html(label);if(this.scrubbing){this.scrubTimeout=setTimeout(function(){scope._scrub(scrubIncrement,time,scrubSpeed,label,index);},scrubSpeed);}},_stopScrub:function(){var scope=this;this.listen=true;this.scrubbing=false;clearTimeout(this.scrubTimeout);$('#previewThumbs').find('img').hide();$('#playSpeedBox').hide();this.scrubSpeedIndex=0;$('#playSpeedBox .arrows').removeClass('backward forward');var currentSeconds=VideoController.currentSeconds;scope.movieLength=scope.movieLength===Infinity?Model.App.movie.duration_seconds:scope.movieLength;if(currentSeconds!==0&&!Model.App.trailer&&!this.scrubbing){API.updateSeek({seek_time:currentSeconds,duration:scope.movieLength,id:scope.passId},function(a){},function(a,errorCode){TVA.log(a.errorThrown.responseText);Model.App.errorCode=errorCode;});}},_getDiff:function(){return(this.scrubTime-VideoController.getCurrentTime());},genericBar:function(el,fill){if(!isFinite(fill)||fill===null)
fill=0;$(el).css({width:fill+'%'});},_bufferBar:function(buffer){this.genericBar('#buffer',buffer);},_progressBar:function(progress){this.genericBar('#progress',progress);},_toggleClass:function(el,c1,c2){$(el).removeClass(c1).addClass(c2);},_lockRootVC:function(lock){var islocked=ViewControllerManager.find('Root').locked;if((islocked&&!lock)||(!islocked&&lock)){ViewControllerManager.find('Root').locked=lock;}},_fakeBufferingProgress:function(progress){if((settings.device==='samsung_tizen'||settings.device==='panasonic')&&!this.scrubbing&&isFinite(progress)){var random=Util._generateRandomInt(0,5);var sbp=this.simulateBufferProgress;sbp=(sbp>=progress+random)?sbp:progress+random;sbp=sbp<=100?sbp:100;this._bufferBar(sbp);this.simulateBufferProgress=sbp;}},createSubtitleOptions:function(data){if(!this.children.playerLanguages){var callBacks={clickCB:this.subtitleClickCB};var carouselData=[];carouselData.push('Captions off');for(var i=0;i<data.length;i++){carouselData.push(data[i].language_name);}
var params={activate:false,carouselData:carouselData};this.removeChildren();WidgetManager.addWidget(this,'playerLanguages','#captionLanguageList',callBacks,params);}
this.children['playerLanguages'].view.scrollTo(0,Model.App.captionsIndex||this.captionsIndex);},subtitleClickCB:function(){var player=ViewControllerManager.find('Player');player.changeSubtitleLanguage(this.pos);},changeSubtitleLanguage:function(i){Model.App.captionsIndex=i;if(Model.App.captionsIndex===0){this.captions=false;this.clearCaptions();}else{this.captions=true;this.captionsIndex=Model.App.captionsIndex-1;this.getSubtitles(this.SubtitleOptions[this.captionsIndex]);$('#playerLanguages .gridElement p').removeClass('selected');$('#playerLanguages').find('.gridElement:nth-child('+((Model.App.captionsIndex||0)+1)+') p').addClass('selected');}
this.hideLangOptions();this.findCaption=true;},getSubtitles:function(lang){var scope=this;API.getSubtitles(lang.url,function(res){scope.subtitleText=res;scope.parseSubtitles(scope.subtitleText);},function(res,errorCode){});},clearCaptions:function(){$('#captions').html('');this.subTitles=[];},parseSubtitles:function(cap){var subtitleText=cap.split(/[\n\r][\n\r]/g);for(var i=0;i<subtitleText.length;i++){if(subtitleText[i]!=='WEBVTT'&&subtitleText[i]!==''){var obj={};var caption=subtitleText[i].split(/[\n\r]/);var timeCodes=caption[0];timeCodes=timeCodes.split('-->');obj['start']=this.timeCodeToSeconds(timeCodes[0]);obj['end']=this.timeCodeToSeconds(timeCodes[1]);var ccText='';for(var j=1;j<caption.length;j++){ccText+='<p>'+caption[j]+'</p>';}
obj['text']=ccText;this.subTitles.push(obj);}}},runSubtitles:function(seconds,findCaption){var caption='';if(findCaption){this.findCaption=false;if(seconds>=this.subTitles[this.captionIndex].start){for(var i=this.captionIndex;i<this.subTitles.length;i++){if(seconds<this.subTitles[i].end){this.captionIndex=i;break;}}}else{for(var j=this.captionIndex;j>0;j--){if(seconds>=this.subTitles[j].start){if(seconds<this.subTitles[j].end){this.captionIndex=j;break;}}}}}
for(var k=0;k<this.captionIndex+1;k++){if(this.subTitles[k]){if(seconds>=this.subTitles[k].start&&seconds<=this.subTitles[k].end){caption+=this.subTitles[k].text;}}}
if(seconds>=this.subTitles[this.captionIndex].end){this.captionIndex++;}
$('#captions').html(caption);},showLangOptions:function(){this.playerLangOptions=true;var player=ViewControllerManager.find('Player');$('#PlayerControls').css({'transition-duration':'0s'});$('#PlayerControls').addClass('languageOptions');this.createSubtitleOptions(this.SubtitleOptions);$('#playerLanguages').find('.gridElement p').removeClass('selected');if(Model.App.captionsIndex===undefined||Model.App.captionsIndex===null){$('#playerLanguages').find('.gridElement p').eq(0).addClass('selected');}else{$('#playerLanguages').find('.gridElement p').eq(Model.App.captionsIndex).addClass('selected');}
player.navigation.playerLanguages={Down:'playPause'};player.navigation.rewind.Up='playerLanguages';player.navigation.playPause.Up='playerLanguages';player.navigation.forward.Up='playerLanguages';player.navigation.CC.Up='playerLanguages';},hideLangOptions:function(){this.playerLangOptions=false;var player=ViewControllerManager.find('Player');$('#PlayerControls').removeClass('languageOptions');TVA.setFocus('playPause');player.activeChild='playPause';player.navigation.rewind.Up='';player.navigation.playPause.Up='';player.navigation.forward.Up='';player.navigation.CC.Up='';},timeCodeToSeconds:function(timecode){if(!timecode)timecode=0;timecode=timecode.replace(' ','');timecode=timecode.split(':');var seconds=0;switch(timecode.length){case 1:seconds+=parseFloat(timecode[0]);break;case 2:seconds+=parseFloat(timecode[0])*60;seconds+=parseFloat(timecode[1]);break;case 3:seconds+=parseFloat(timecode[0])*3600;seconds+=parseFloat(timecode[1])*60;seconds+=parseFloat(timecode[2]);break;}
return seconds;}}));})();