(function(){"use strict";var base=ViewControllerManager.findClass("ViewControllerNav");ViewControllerManager.newClassDef("SearchVC",Class.create({_extends_:base,_init_:function(args){base.call(this,args);this.activeChild="";this.navigation={};this.searchSuggestionsList={movies:[],cast:[],genre:[]};this.searchResults=[];this.keyword='';this.notFound=false;},onLoad:function(){},render:function(location){var self=this;this._super(location);$('#FlixLogo').hide();$('#backIcon').text(language[Model.App.file.language].common.btn_menu);$('#SearchTitle').text(language[Model.App.file.language].menu.search);$('#ExtraInfo').css({top:'100px',height:'580px',width:'530px'});this.getSuggestions(function(){self.activeChild="";ViewControllerManager.find("Keyboard").activeChild="keyboard-0-0";TVA.setFocus(ViewControllerManager.find("Keyboard").activeChild);},function(){});},getSuggestions:function(onSuccess,onError){var self=this;var key=self.keyword;self.searchSuggestionsList={movies:[],cast:[],genre:[]};if(key!==''&&key.length>1){API.getAutoCompleteSuggestions(key,function(result){if(result.data[0].hasOwnProperty('keywords')){self.notFound=false;$('#searchSuggestions').find('.Grid_Container').empty();if(result.data[0].keywords.hasOwnProperty('movie')){self.searchSuggestionsList.movies=result.data[0].keywords.movie;}
if(result.data[0].keywords.hasOwnProperty('cast')){self.searchSuggestionsList.cast=result.data[0].keywords.cast;}
if(result.data[0].keywords.hasOwnProperty('genre')){self.searchSuggestionsList.genre=result.data[0].keywords.genre;}
self._createSuggestionsList();}
else{self.notFound=true;var text;if(self.keyword===''){text=language[Model.App.file.language].searchScreen.startText;self.searchSuggestionsList.movies=[text];}
else{text=language[Model.App.file.language].searchScreen.noContent;self.searchSuggestionsList.movies=[text];}
$('#searchSuggestions').find('.Grid_Container').empty();self._createSuggestionsList();}
onSuccess&&onSuccess();},function(result,errorCode){onError&&onError();Model.App.errorCode=errorCode;home.publish('Error');});}else{self.notFound=true;var text;if(self.keyword===''){text=language[Model.App.file.language].searchScreen.startText;self.searchSuggestionsList.movies=[text];}
else{text=language[Model.App.file.language].searchScreen.noContent;self.searchSuggestionsList.movies=[text];}
$('#searchSuggestions').find('.Grid_Container').empty();self._createSuggestionsList();onSuccess&&onSuccess();}},_createSuggestionsList:function(){var self=this;var callBacks={clickCB:this.suggestionsClick,keydownCB:this.onKeyDown,hoverCB:this.onHover};var carouselData=[];for(var i=0;i<self.searchSuggestionsList.movies.length;i++){carouselData.push(self.searchSuggestionsList.movies[i]);}
for(var j=0;j<self.searchSuggestionsList.cast.length;j++){carouselData.push(self.searchSuggestionsList.cast[j]);}
for(var k=0;k<self.searchSuggestionsList.genre.length;k++){carouselData.push(self.searchSuggestionsList.genre[k]);}
var params={activate:true,carouselData:carouselData};WidgetManager.addWidget(self,'searchSuggestions','#SearchContainer',callBacks,params);},suggestionsClick:function(e){var Search=ViewControllerManager.find("Search");var searchSuggestionsList=Search.searchSuggestionsList;var char=TVA.onFocus.charAt(12);var gridClickedElement=char==='_'?TVA.onFocus.substr(0,23):TVA.onFocus.substr(0,24);var elementLength=$('#'+gridClickedElement+'> .content').text().length;var gridClickedContent=$('#'+gridClickedElement+'> .content').text().substr(1,elementLength);var type='';for(var i=0;i<searchSuggestionsList.movies.length;i++){if(searchSuggestionsList.movies[i]===gridClickedContent){type='movie';break;}}
if(type===''){for(var j=0;j<searchSuggestionsList.cast.length;j++){if(searchSuggestionsList.cast[j]===gridClickedContent){type='cast';break;}}}
if(type===''){for(var k=0;k<searchSuggestionsList.genre.length;k++){if(searchSuggestionsList.genre[k]===gridClickedContent){type='genre';break;}}}
e.stopPropagation();Search._defineSearchCall(type,gridClickedContent);},onKeyDown:function(e,keyCode){TVA.log('keydown in Search');switch(keyCode){case Keys.getBind("Up"):break;case Keys.getBind("Down"):break;case Keys.getBind("Left"):var Keyboard=ViewControllerManager.find("Keyboard");if(!Keyboard.hidden){TVA.setFocus(Keyboard.aux_focus);Keyboard.activeChild=Keyboard.aux_focus;$('#searchSuggestions .active').removeClass('active');}
e.stopPropagation();break;}},onHover:function(event){var element=event.target.id;this._enableElement(element);event.stopPropagation();},_defineSearchCall:function(str,name){var self=this;var Keyboard=ViewControllerManager.find("Keyboard");if(str==='movie'){self._getMovieResult(name,function(result){console.log('_getMovieResult onSuccess');console.log(result);self.createCarouselsList();},function(result){Util.hideSpriteLoader();});}
else if(str==='cast'){self._getCastResult(name,function(result){self.createCarouselsList();},function(result){Util.hideSpriteLoader();});}
else if(str==='genre'){self._getGenreResult(name,function(result){self.createCarouselsList();},function(result){Util.hideSpriteLoader();});}
$('#keyboardBox').hide();$('#SearchContainer').hide();$('#searchResult').text(language[Model.App.file.language].searchScreen.searchResultsTitle.replace('[keyword]',name));$('#searchResult').show();Keyboard.hidden=true;},_getMovieResult:function(title,onSuccess,onError){var self=this;Util.showSpriteLoader();API.getMovieSearch(title,function(result){self.searchResults=result.data;onSuccess&&onSuccess(result);},function(result,errorCode){onError&&onError(result);Model.App.errorCode=errorCode;home.publish('Error');});},_getCastResult:function(name,onSuccess,onError){var self=this;Util.showSpriteLoader();API.getCastSearch(name,function(result){self.searchResults=result.data;onSuccess&&onSuccess(result);},function(result,errorCode){onError&&onError(result);Model.App.errorCode=errorCode;home.publish('Error');});},_getGenreResult:function(genre,onSuccess,onError){var self=this;Util.showSpriteLoader();API.getGenreSearch(genre,function(result){self.searchResults=result;onSuccess&&onSuccess(result);},function(result,errorCode){onError&&onError(result);Model.App.errorCode=errorCode;home.publish('Error');});},onResultClick:function(){var Search=ViewControllerManager.find("Search");var pos=this.pos+(this.columns*this.row);var movie=Search.searchResults[pos];var movie_id=movie.id;Search.addDetailsScreen(movie_id);},addDetailsScreen:function(id){var Home=ViewControllerManager.find('Home');Util.showSpriteLoader();API.getMovie(id,function(data){Model.App['returnFromDetailsTo']={parent:'search_results',screen:'search_results'};Model.App['movie']=data;var vc=ViewControllerManager.find("Details");$('#search_results').hide();$('#searchResult').hide();Home.addChild(vc,'#screens');},function(res,errorCode){Model.App.errorCode=errorCode;Home.publish('Error');});},onResultKeyDown:function(e,keyCode){var Search=ViewControllerManager.find("Search");if(keyCode===Keys.getBind("Back")){var Keyboard=ViewControllerManager.find("Keyboard");if(Keyboard.hidden){Search.removeChild('search_results');$('#screens').remove('search_results');$('#keyboardBox').show();$('#SearchContainer').show();$('#searchResult').empty();$('#searchResult').hide();Search.children.searchSuggestions.view.enable();Keyboard.hidden=false;e.stopPropagation();}}},createCarouselsList:function(){var self=this;var callBacks={clickCB:self.onResultClick,keydownCB:self.onResultKeyDown};var carouselData=self.searchResults.data||self.searchResults;var params={activate:true,carouselData:carouselData};WidgetManager.addWidget(self,'search_results','#screens',callBacks,params);Util.hideSpriteLoader();},onUnload:function(){this.activeChild='';TVA.setFocus(this.activeChild);$('#FlixLogo').show();$('#ExtraInfo').css({top:'200px',height:'420px',width:'470px'});}}));})();