(function(){"use strict";var base=ViewControllerManager.findClass("ViewControllerNav");ViewControllerManager.newClassDef("CarouselsListVC",Class.create({_extends_:base,_init_:function(args){base.call(this,args);this.previousChild=null;this.activeChild='default';this.navigation={};this.pos=0;this.vpos=0;this.hpos=0;this.size=0;this.maxEl=3;this.activePos=0;this.offset=0;this.images=[];this.text=[];this.contents=[];this.screenPadding=0;this.listenKeys=true;this.rows=null;this.columns=null;this.Nrow=null;this.Ncol=null;this.row=0;this.verticalMargin=6;this.horizontalMargin=6;this.cloneIndex=null;this.x=0;this.y=0;this.orientation='vertical';this.keydownCB=null;this.clickCB=null;this.hoverCB=null;this.mouseOutCB=null;this.hover=false;this.containerPos={x:0,y:0};this.cellDims={width:100,height:100};this.performance=false;this.noSibling=true;this.hiddenElements={};this.directions={horizontal:{'1':'Left','-1':'Right'},vertical:{'1':'Up','-1':'Down'}};this.showArrows=true;this.scrolling=false;Model.newModel(this.name);this.previousAdded=null;this.childIndexList={};this.childIndex=0;},init:function(params){if(params.gridPos){$(this.rootID+' > .action').css({top:params.gridPos.y,left:params.gridPos.x,width:params.gridPos.width,height:params.gridPos.height});}
this.columns=params.columns||0;this.childIndex=0;this.setArrows();},addCarousel:function(widgetName,callBacks,carouselData,title,widgetType){var params={carouselData:carouselData};this.childIndexList[widgetName]=this.childIndex;this.childIndex++;this.rows=this.childIndex;callBacks.parentListMouseOutCB=this.mouseOut;callBacks.parentListHoverCB=this.onHover;if(widgetType){params.widgetType=widgetType;}
var category='<div id="category_'+widgetName+'"><p class="title">'+title+'</p></div>';$(this.rootID+' .CarouselsList_Container').append(category);if(WidgetManager.find(widgetName)){WidgetManager.addWidget(this,widgetName,'#category_'+widgetName,callBacks,params);}else{var vc=ViewControllerManager.find(widgetName);this.addChild(vc,'#category_'+widgetName);}
var h=parseInt($('#'+widgetName+' .action').css('height').replace('px',''));var titleHeight=parseInt($('#category_'+widgetName+' .title').css('height').replace('px',''));$('#'+widgetName).css({height:h,top:(titleHeight>0?titleHeight+40:titleHeight)});h+=titleHeight;$('#category_'+widgetName).css({height:h*1.3,position:'absolute'});this.navigation[widgetName]={};if(this.previousAdded){this.navigation[this.previousAdded]['Down']=widgetName;this.navigation[widgetName]['Up']=this.previousAdded;var el=$('#category_'+this.previousAdded);if(!this.previousAdded||!el[0])
return;h=parseInt(el.css('height').replace('px',''));if(el.position().top>0){h=h+el.position().top;}
$('#category_'+widgetName).css({top:h});}
this.previousAdded=widgetName;},onUnload:function(){this.pos=0;this.images=[];this.text=[];this.contents=[];TVA.offFocus(TVA.onFocus);this.previousAdded=null;},onLoad:function(){this._loadVC();this.images=[];this.text=[];this.pos=0;this.contents=[];this.clickEvent=null;},_loadVC:function(){},render:function(location){this._super(location);this.enable();this.reset();},onKeyDown:function(e,keyCode){TVA.log('keydown in '+this.name);if(this.name==='restaurantList'){TVA.log('wait');}
if(this.listenKeys&&Model.App.listen){switch(keyCode){case Keys.getBind("Back"):break;case Keys.getBind("Up"):this.navUpElement(e);break;case Keys.getBind("Down"):this.navDownElement(e);break;case Keys.getBind("Left"):this.navLeftElement(e);break;case Keys.getBind("Right"):this.navRightElement(e);break;case Keys.getBind("Enter"):$('#'+TVA.onFocus).click();e.stopPropagation();break;case Keys.getBind("Cross"):$('#'+TVA.onFocus).click();e.stopPropagation();break;}
this.keydownCB&&this.keydownCB(e,keyCode);}
if(this.scrolling){e.stopPropagation();}},_navigate:function(direction,e){this.previousChild=this.activeChild;var nextChild=this.navigation[this.activeChild][direction];$('#'+this.activeChild+' .active').removeClass('active');if(nextChild&&this.children[nextChild]){this.noSibling=false;$(this.children[this.activeChild].view.rootID+' > .Arrow').hide();this.children[nextChild].view.enable();this.children[nextChild].view.toggleArrows();var top=$('#category_'+nextChild).position().top;var height=parseInt($('#category_'+nextChild).css('height').replace('px',''));var containerPosition=$(this.rootID+' .CarouselsList_Container').position().top;var bound=parseInt($(this.rootID+' .action').css('height').replace('px',''));var actionTop=0;var homeTop=0;if(this.activeChild=='home_now_showing'){homeTop=-264;}else if(this.activeChild=='home_red_carpet'){homeTop=-751;}else if(this.activeChild=='home_upcoming'){homeTop=-1200;}else if(this.activeChild=='myMovies_reminders'&&Model.myMovies.films.active_films.length===0){homeTop=0;}else if(this.activeChild=='myMovies_reminders'){homeTop=-317;}
if(direction==='Down'&&(containerPosition+top+height>bound)){var delt=bound-(containerPosition+top+height);if(homeTop!=0){$(this.rootID+' .CarouselsList_Container').css({top:homeTop});}else
$(this.rootID+' .CarouselsList_Container').css({top:containerPosition+delt});}else if(direction==='Up'&&(containerPosition+top<actionTop)){var delt=actionTop-(containerPosition+top);if(homeTop!=0){$(this.rootID+' .CarouselsList_Container').css({top:homeTop});}else
$(this.rootID+' .CarouselsList_Container').css({top:containerPosition+delt});}
e.stopPropagation();e.stopImmediatePropagation();}else if($(this.rootID).find('#'+nextChild).length){this.noSibling=false;TVA.setFocus(nextChild);this.activeChild=nextChild;this.activateParent();nextChild=this.navigation[this.activeChild][direction];if(nextChild){nextChild=nextChild.replace('_Overlay','');if(!document.getElementById(nextChild)&&this.hiddenElements[nextChild]){}}
e.stopPropagation();e.stopImmediatePropagation();this.gridNavCallBack&&this.gridNavCallBack();}else{this.noSibling=true;}},activateParent:function(){$(this.rootID+' .gridElement').removeClass('active');$('#'+this.activeChild.replace('_Overlay','')).addClass('active');ViewControllerManager.ViewControllers[this.name].parentVC.activeChild=this.name;},_targetItem:function(e,direction){var targetChild=this.navigation[this.activeChild][direction];if(targetChild){this._navigate(direction,e);}else{this.noSibling=true;}
this.toggleArrows(direction);},mouseOut:function(e){},setArrows:function(){var actionWidth=parseInt($(this.rootID+'  > .action').css('width').replace('px',''));var actionHeight=parseInt($(this.rootID+' > .action').css('height').replace('px',''));var actionTop=parseInt($(this.rootID+' > .action').css('top').replace('px',''));var actionLeft=parseInt($(this.rootID+' > .action').css('left').replace('px',''));var arrowWidth=parseInt($(this.rootID+' > .Left_Arrow').css('width').replace('px',''));var arrowHeight=parseInt($(this.rootID+' > .Left_Arrow').css('height').replace('px',''));var top=((actionHeight/2)-(arrowHeight/2))+actionTop;var left=actionLeft-arrowWidth;$(this.rootID+' > .Left_Arrow').css({top:top+'px',left:left+'px'});arrowWidth=parseInt($(this.rootID+' > .Right_Arrow').css('width').replace('px',''));arrowHeight=parseInt($(this.rootID+' > .Right_Arrow').css('height').replace('px',''));top=((actionHeight/2)-(arrowHeight/2))+actionTop;left=actionWidth+actionLeft;$(this.rootID+' > .Right_Arrow').css({top:top+'px',left:left+'px'});arrowWidth=parseInt($(this.rootID+' > .Up_Arrow').css('width').replace('px',''));arrowHeight=parseInt($(this.rootID+' > .Up_Arrow').css('height').replace('px',''));top=actionTop-arrowHeight;left=((actionWidth/2)-(arrowWidth/2))+actionLeft;$(this.rootID+' > .Up_Arrow').css({top:top+'px',left:left+'px'});arrowWidth=parseInt($(this.rootID+' > .Down_Arrow').css('width').replace('px',''));arrowHeight=parseInt($(this.rootID+' > .Down_Arrow').css('height').replace('px',''));top=actionHeight+actionTop;left=((actionWidth/2)-(arrowWidth/2))+actionLeft;$(this.rootID+' > .Down_Arrow').css({top:'630px',left:left+'px'});$(this.rootID+' > .Left_Arrow').hide();$(this.rootID+' > .Right_Arrow').hide();$(this.rootID+' > .Up_Arrow').hide();$(this.rootID+' > .Down_Arrow').hide();},hideArrows:function(e){$(this.rootID+' > .Arrow').removeClass('active');$(this.rootID+' > .Arrow').hide();},toggleArrows:function(direction){this.row=this.childIndexList[this.activeChild];if(this.showArrows){if(this.orientation==='horizontal'){if(this.pos<this.columns-1){$(this.rootID+' > .Right_Arrow').show();}else{$(this.rootID+' > .Right_Arrow').hide();}
if(this.pos>0){$(this.rootID+' > .Left_Arrow').show();}else{$(this.rootID+' > .Left_Arrow').hide();}
$(this.rootID+' > .Down_Arrow').hide();$(this.rootID+' > .Up_Arrow').hide();}else if(this.orientation==='vertical'){if(this.row<this.rows-1){$(this.rootID+' > .Down_Arrow').show();}else{$(this.rootID+' > .Down_Arrow').hide();}
if(this.row>0&&this.row!=0){$(this.rootID+' > .Up_Arrow').show();}else{$(this.rootID+' > .Up_Arrow').hide();}
$(this.rootID+' > .Left_Arrow').hide();$(this.rootID+' > .Right_Arrow').hide();}
}else{$(this.rootID+' > .Right_Arrow').hide();$(this.rootID+' > .Left_Arrow').hide();$(this.rootID+' > .Down_Arrow').hide();$(this.rootID+' > .Up_Arrow').hide();}},navLeftElement:function(e){if(e.type==='click'){this.hover=true;}
TVA.log('navLeftElement in '+this.name);if(this.listenKeys){this._targetItem(e,"Left");}else{e.stopPropagation();}},navRightElement:function(e){if(e.type==='click'){this.hover=true;}
TVA.log('navRightElement in '+this.name);if(this.listenKeys){this._targetItem(e,"Right");}else{e.stopPropagation();}},navUpElement:function(e){if(e.type==='click'){this.hover=true;}
if(this.listenKeys){this._targetItem(e,"Up");}else{e.stopPropagation();}
var home=ViewControllerManager.find('Home');if(home.children.categoriesList.view.activeChild==='home_featured')
$('#featuredCounter').addClass('active');},navDownElement:function(e){if(e.type==='click'){this.hover=true;}
if(this.listenKeys){this._targetItem(e,"Down");}else{e.stopPropagation();}
var home=ViewControllerManager.find('Home');if(home.children.categoriesList.view.activeChild==='home_now_showing')
$('#featuredCounter').removeClass('active');},updateGrid:function(){this.hiddenElements={};var maxCarouselElements=this.size;var cellCount=0;$(this.rootID+' .Grid_Container').html('');for(var i=0;i<this.rows;i++)
{var row='';if($(this.rootID+' .Grid_Container').find('#Grid'+this.cloneIndex+'_row_'+i).length){row='Grid'+this.cloneIndex+'_row_'+i;}else{row='Grid'+this.cloneIndex+'_row_'+i;var inlineStyle='style="position:absolute;width:1280px;height:'+this.cellDims.height+'px"';$(this.rootID+' .Grid_Container').append('<div id="'+row+'" class="gridRow" '+inlineStyle+'></div>');}
var maxHeight=0;for(var j=0;j<this.columns;j++)
{var elementId=row+'_Item_pos_'+j;if(this.contents[cellCount]){var content=this.contents[cellCount].content||'';if($(this.rootID+' .Grid_Container #'+row+' #'+elementId)[0]){$(this.rootID+' .Grid_Container #'+row+' #'+elementId+' .content').html(content);}else
{var inlineStyle='position:absolute;';var cellWidth=this.cellDims.width>0?'width:'+this.cellDims.width+'px;':'';var cellHeight=this.cellDims.height>0?'height:'+this.cellDims.height+'px;':'';inlineStyle+=cellWidth;inlineStyle+=cellHeight;var el=document.createElement('DIV');el.setAttribute('id',elementId);el.setAttribute('class','gridElement');el.setAttribute('style',inlineStyle);var elContent=document.createElement('DIV');elContent.setAttribute('class','content');elContent.setAttribute('style',"position:absolute;");elContent.innerHTML=content;var elOverlay=document.createElement('DIV');elOverlay.setAttribute('id',elementId+'_Overlay');elOverlay.setAttribute('class','Grid_Item_Overlay hoveritem');elOverlay.setAttribute('style',"position:absolute;width:100%;height:100%;");el.appendChild(elContent);el.appendChild(elOverlay);if(this.performance){var rootEl=document.getElementById(this.name).children[0];var rootX=parseInt(rootEl.style.left.replace('px','')||0);var containerX=parseInt(rootEl.children[0].children[0].style.left.replace('px',''));var width=parseInt(el.style.width.replace('px',''));var elementX=j*width;if(rootX+containerX+elementX>1280||(rootX+containerX+elementX)+width<0){el.style.left=elementX+'px';this.hiddenElements[elementId]=el;this.adjustElement(row,el,elementId,j);}else{document.getElementById(row).appendChild(el);this.adjustElement(row,el,elementId,j);}}else{document.getElementById(row).appendChild(el);this.adjustElement(row,el,elementId,j);}}}
cellCount++;}
var y=0;if(i>0){var rowID='Grid'+this.cloneIndex+'_row_'+(i-1);var top=$(this.rootID+' .Grid_Container #'+rowID).position().top;y=top+$(this.rootID+' .Grid_Container #'+rowID).height()+6;}else{y=0;}
if($(this.rootID+' .Grid_Container #'+row).position().top===0){$(this.rootID+' .Grid_Container #'+row).css({top:y});}
var rowEls=$(this.rootID+' .Grid_Container .gridRow');var totalGridHeight=0;for(var rowIndex=0;rowIndex<rowEls.length;rowIndex++){totalGridHeight+=$(rowEls[rowIndex]).height();}
$(this.rootID+' .Grid_Container').css({height:totalGridHeight});}
this.toggleArrows();},adjustElement:function(row,el,elementId,j){if(this.autoSizeRows){var height=$(el.children[0]).css('height');height=parseInt(height.replace('px',''));el.style.height=(height+this.cellDims.height)+'px';document.getElementById(row).style.height=(height+this.cellDims.height)+'px';var top=(parseInt(el.style.height.replace('px',''))/2)-(height/2);el.children[0].style.top=top+'px';}else{el.children[0].style.width='100%';el.children[0].style.height='100%';}
var width=(parseInt(el.style.width.replace('px',''))+this.horizontalMargin)*j;el.style.left=width+'px';},onButtonOut:function(e){$(this.rootID+' > .hoverButton').removeClass('active');e.stopPropagation();},onButtonHover:function(e){this.row=this.childIndexList[this.activeChild];this.hover=true;$(this.rootID+' div .Arrow').hide();$(this.rootID+' > .'+e.target.classList[0]).addClass('active');e.stopPropagation();},onHover:function(event){if(this.parentVC.name==='Home')
return;var scope=ViewControllerManager.find(this.parentVC.name);if(scope.previousChild!==null&&scope.previousChild!==scope.activeChild){$('#'+scope.previousChild+' > .Arrow').hide();}
scope.previousChild=scope.activeChild;scope.hover=true;scope._setGridIndex();scope.toggleArrows();event.stopPropagation();},_setGridIndex:function(id){this.row=this.childIndexList[this.activeChild];},clickEvent:function(){},scrollLeft:function(scrollAmount){this.scroll(-1,scrollAmount,'horizontal');},scrollRight:function(scrollAmount){this.scroll(1,scrollAmount,'horizontal');},scrollUp:function(scrollAmount){this.scroll(-1,scrollAmount,'vertical');},scrollDown:function(scrollAmount){this.scroll(1,scrollAmount,'vertical');},scroll:function(direction,distance,orientation){this.listenKeys=false;this.scrolling=true;var scope=this;var newPos='0px';var animCSS={};if(orientation==='vertical'){var y=$(this.rootID+' .Grid_Container').position().top;var dy=(distance||53)*direction;var clipY=$(this.rootID+' .clip').position().top;var newPos=Math.round(dy+y);this.containerPos.y=newPos;this.newPos=newPos+'px';animCSS={top:this.newPos};this._animComplete({top:this.containerPos.y,direction:this.directions[orientation][direction]});}else if(orientation==='horizontal'){var x=$(this.rootID+' .Grid_Container').position().left;var dx=(distance||53)*direction;this.newPos=Math.round((dx+x))+'px';animCSS={'left':this.newPos};this.containerPos.x=Math.round(dx+x);this._animComplete({left:this.containerPos.x,direction:this.directions[orientation][direction]});}
$(this.rootID+' .Grid_Container').css(animCSS);if(this.performance){this.cleanOffScreen(this.directions[orientation][direction]);}},_animComplete:function(params){var interval=80;clearTimeout(this.animCompleteInterval);var scope=this;if(typeof params.left==='number'){if(Math.round($(this.rootID+' .Grid_Container').position().left)===Math.round(params.left)){this.listenKeys=true;this.scrolling=false;if(this.performance){}}else{this.animCompleteInterval=setTimeout(function(){scope._animComplete(params);},interval);}}else if(typeof params.top==='number'){if(Math.round($(this.rootID+' .Grid_Container').position().top)===Math.round(params.top)){this.listenKeys=true;this.scrolling=false;if(this.performance){}}else{this.animCompleteInterval=setTimeout(function(){scope._animComplete(params);},interval);}}},cleanOffScreen:function(direction){if(direction==='Right'){var findOffScreen=true;for(var i=this.pos;i<this.columns&&findOffScreen;i++){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(!document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.pushOnScreen(el,j);}}}
findOffScreen=true;for(var i=this.pos;i>=0&&findOffScreen;i--){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(this.isOffscreen(element)&&document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){var el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.popOffScreen(el,j);}}}}else if(direction==='Left'){var findOffScreen=true;for(var i=this.pos;i>=0&&findOffScreen;i--){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(!document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.pushOnScreen(el,j);}}}
findOffScreen=true;for(var i=this.pos;i<this.columns&&findOffScreen;i++){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(this.isOffscreen(element)&&document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){var el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.popOffScreen(el,j);}}}}
},isElementObscured:function(overlayElement,autoScroll,direction){var id=overlayElement.replace('_Overlay','');var rootEl=document.getElementById(this.name);var element=null;if(document.getElementById(id)){element=document.getElementById(id);overlayElement=document.getElementById(overlayElement);}else if(this.hiddenElements[id]){element=this.hiddenElements[id];overlayElement=element.children[1];}
var container=rootEl.children[0].children[0].children[0];if((direction==='Left'||direction==='Right')&&this.orientation==='horizontal'){var matrixLeft=$(this.rootID+' .Grid_Container').position().left;var actionZoneWidth=rootEl.children[0].style.width.replace('px','');matrixLeft=container.style.left.replace('px','');matrixLeft=parseInt(matrixLeft===''?0:matrixLeft);var pos={left:element.style.left.replace('px',''),top:element.style.top.replace('px','')};var width=$(overlayElement).width();var scrollAmount=0;var scroll=autoScroll||true;var x=parseInt(pos.left)+matrixLeft;if(x<(0+this.screenPadding)){if(scroll){var dX=Math.abs(x)+this.screenPadding;this.scrollRight(dX);}
return true;}else if((x+width)>(0+actionZoneWidth)-this.screenPadding){scrollAmount=(x+width)-(actionZoneWidth-this.screenPadding);if(scroll){this.scrollLeft(scrollAmount);}
return true;}else{return false;}}else if((direction==='Up'||direction==='Down')&&this.orientation==='vertical'){var matrixTop=$(this.rootID+' .Grid_Container').position().top;var actionZoneHeight=parseInt(rootEl.children[0].style.height.replace('px',''));matrixTop=container.style.top.replace('px','');matrixTop=parseInt(matrixTop===''?0:matrixTop);var pos=$(overlayElement).parent().parent().position();var height=$(overlayElement).height();var scrollAmount=0;var scroll=autoScroll||true;var y=pos.top+matrixTop;if(y<0)
{if(scroll){var dY=Math.abs(y)+this.screenPadding;this.scrollDown(dY);this.offset--;}
return true;}else if((y+height)>(actionZoneHeight)-this.screenPadding)
{scrollAmount=(y+height)-(actionZoneHeight-this.screenPadding);if(scroll){this.scrollUp(scrollAmount);this.offset++;}
return true;}else{return false;}}},hideAllOffscreen:function(){var noRows=document.getElementById(this.name).children[0].children[0].children[0].children.length;var noCols=document.getElementById(this.name).children[0].children[0].children[0].children[0].children.length;for(var i=0;i<noRows;i++){for(var j=0;j<noCols;j++){var elId='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+j;if(this.isOffscreen(elId)){this.popOffScreen(elId,i);}}}},pushOnScreen:function(element,row){if(document.getElementById(element)){element=document.getElementById(element);}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
document.getElementById(this.name).children[0].children[0].children[0].children[row].appendChild(element);},popOffScreen:function(element,row){if(document.getElementById(element)){this.hiddenElements[element]=document.getElementById(element);element=this.hiddenElements[element];}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
document.getElementById(this.name).children[0].children[0].children[0].children[row].removeChild(element);},isOffscreen:function(element){var left,rootX,elementX,containerX,width,margin;var rootEl=document.getElementById(this.name).children[0];if(document.getElementById(element)){element=document.getElementById(element);}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
left=element.style.left.replace('px','');left=left===''?0:left;rootX=parseInt(rootEl.style.left.replace('px','')||0);elementX=parseInt(left);containerX=parseInt(rootEl.children[0].children[0].style.left.replace('px',''));width=parseInt(element.style.width.replace('px',''));return rootX+containerX+elementX>1280||(rootX+containerX+elementX)+width<0;},onClick:function(e){this.clickCB&&this.clickCB(e);},reset:function(){$(this.rootID+' .CarouselsList_Container').css({top:'0px'});this._unloadChildren();$(this.rootID+' .CarouselsList_Container').html('');this.previousAdded=null;},gridNavCallBack:function(){}}));})();