(function(){'use strict';var base=ViewControllerManager.findClass('ViewControllerNav');ViewControllerManager.newClassDef('GridVC',Class.create({_extends_:base,_init_:function(args){base.call(this,args);this.previousChild=null;this.activeChild='Grid_row_0_Item_pos_0_Overlay';this.navigation={};this.pos=0;this.vpos=0;this.hpos=0;this.size=0;this.maxEl=3;this.activePos=0;this.offset=0;this.images=[];this.text=[];this.contents=[];this.screenPadding=0;this.listenKeys=true;this.rows=null;this.columns=null;this.Nrow=null;this.Ncol=null;this.row=0;this.verticalMargin=6;this.horizontalMargin=6;this.cloneIndex=null;this.x=0;this.y=0;this.orientation='vertical';this.keydownCB=null;this.clickCB=null;this.hoverCB=null;this.mouseOutCB=null;this.parentListHoverCB=null;this.parentListMouseOutCB=null;this.containerPos={x:0,y:0};this.cellDims={width:100,height:100};this.performance=false;this.noSibling=true;this.hiddenElements={};this.directions={horizontal:{'1':'Left','-1':'Right'},vertical:{'1':'Up','-1':'Down'}};this.showArrows=true;this.scrolling=false;this.infinite=false;this.hover=false;this.readyToSetScroll=false;this.scrollVerticalIndex=0;this.scrollHorizontalIndex=0;Model.newModel(this.name);},init:function(params){this.row=0;if(params.gridPos){$(this.rootID+' .action').css({top:params.gridPos.y,left:params.gridPos.x,width:params.gridPos.width,height:params.gridPos.height});}
this.scrollVerticalIndex=0;this.scrollHorizontalIndex=0;this.infinite=params.loop||false;this.performance=params.performance||false;this.showArrows=params.showArrows||false;this.autoSizeRows=params.autoSizeRows||false;this.cellDims.width=params.cellWidth||0;this.cellDims.height=params.cellHeight||0;this.cloneIndex=params.cloneIndex?params.cloneIndex:'';this.orientation=params.orientation||'vertical';this.rows=params.rows||0;this.columns=params.columns||0;this.x=params.x||0;this.y=params.y||0;this.screenPadding=params.padding||0;this.contents=params.contents||[];this.maxEl=params.length;this.offset=0;this.size=params.contents.length;this.pos=0;this.verticalMargin=params.verticalMargin||this.verticalMargin;this.horizontalMargin=params.horizontalMargin;if(this.rows>0)
{this.Nrow=Math.ceil(this.size/this.rows);this.Ncol=this.Nrow;this.columns=this.Nrow;}else if(this.columns>0){this.Ncol=Math.ceil(this.size/this.columns);this.rows=this.Ncol;this.Nrow=this.Ncol;}else{return;}
var cellCount=0;for(var i=0;i<this.rows;i++)
{for(var j=0;j<this.columns;j++)
{var child='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+j+'_Overlay';this.navigation[child]={};if(i===0)
{if(j===0&&j>1)
{this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j+1)+'_Overlay';if(this.infinite){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(this.columns-1)+'_Overlay';}}else if(j===this.columns-1&&j>0)
{this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j-1)+'_Overlay';if(this.infinite){this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_0_Overlay';}}else
{if(j>0){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j-1)+'_Overlay';}
if(this.contents[cellCount+1]){this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j+1)+'_Overlay';}
if(this.infinite&&j===0){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(this.columns-1)+'_Overlay';}}
if(this.contents[cellCount+this.columns]){this.navigation[child]['Down']='Grid'+this.cloneIndex+'_row_'+(i+1)+'_Item_pos_'+(j)+'_Overlay';}else if((this.contents.length-(cellCount+1))>0&&params.cloneIndex!==1){var a=this.columns*(this.rows-1);var aux=this.contents.length-a;this.navigation[child]['Down']='Grid'+this.cloneIndex+'_row_'+(i+1)+'_Item_pos_'+(aux-1)+'_Overlay';}}else if(i===this.rows-1)
{if(j===0&&j>1)
{this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j+1)+'_Overlay';}else if(j===this.columns-1&&j>0)
{this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j-1)+'_Overlay';if(this.infinite){this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_0_Overlay';}}else
{if(j>0){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j-1)+'_Overlay';}
if(this.contents[cellCount+1]){this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j+1)+'_Overlay';}
if(this.infinite&&j===0){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(this.columns-1)+'_Overlay';}}
this.navigation[child]['Up']='Grid'+this.cloneIndex+'_row_'+(i-1)+'_Item_pos_'+(j)+'_Overlay';}else{if(j===0)
{this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j+1)+'_Overlay';this.navigation[child]['Up']='Grid'+this.cloneIndex+'_row_'+(i-1)+'_Item_pos_'+(j)+'_Overlay';}else if(j===this.columns-1)
{if(j>0){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j-1)+'_Overlay';}
this.navigation[child]['Up']='Grid'+this.cloneIndex+'_row_'+(i-1)+'_Item_pos_'+(j)+'_Overlay';if(this.infinite){this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_0_Overlay';}}else
{if(j>0){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j-1)+'_Overlay';}
if(this.contents[cellCount+1]){this.navigation[child]['Right']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(j+1)+'_Overlay';}
this.navigation[child]['Up']='Grid'+this.cloneIndex+'_row_'+(i-1)+'_Item_pos_'+(j)+'_Overlay';if(this.infinite&&j===0){this.navigation[child]['Left']='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+(this.columns-1)+'_Overlay';}}
if(this.contents[cellCount+this.columns]){this.navigation[child]['Down']='Grid'+this.cloneIndex+'_row_'+(i+1)+'_Item_pos_'+(j)+'_Overlay';}else if((this.contents.length-(cellCount+1))>0&&params.cloneIndex!==1){var a=this.columns*(this.rows-1);var aux=this.contents.length-a;this.navigation[child]['Down']='Grid'+this.cloneIndex+'_row_'+(i+1)+'_Item_pos_'+(aux-1)+'_Overlay';}}
cellCount++;}}
$(this.rootID+' .Grid_Container').css({'transition-duration':'0s'});$(this.rootID+' .Grid_Container').css({left:this.x});this.readyToSetScroll=true;this.updateGrid();this.previousChild=this.activeChild;this.activeChild='Grid'+this.cloneIndex+'_row_0_Item_pos_0_Overlay';var clipY=$(this.rootID+' .clip').position().top;$(this.rootID+' .Grid_Container').css({top:this.y-clipY});if(params.activate){this.enable();$('#'+this.activeChild.replace('_Overlay','')).addClass('active');}
$(this.rootID+' .Left_Arrow').attr('id',this.name+'_Left_Arrow');$(this.rootID+' .Right_Arrow').attr('id',this.name+'_Right_Arrow');$(this.rootID+' .Up_Arrow').attr('id',this.name+'_Up_Arrow');$(this.rootID+' .Down_Arrow').attr('id',this.name+'_Down_Arrow');if(this.performance){this.hideAllOffscreen();this.hideAllRowsOffscreen();}
if(this.infinite){this.adjustSiblings('Grid'+this.cloneIndex+'_row_0_Item_pos_0');}
this.setArrows();$(this.rootID+' .Grid_Container').css({'transition-duration':'0.2s'});},onUnload:function(){this.pos=0;this.images=[];this.text=[];this.contents=[];TVA.offFocus(TVA.onFocus);},onLoad:function(){this._loadVC();this.images=[];this.text=[];this.pos=0;this.contents=[];this.clickEvent=null;},_loadVC:function(){},render:function(location){this._super(location);this.enable();this.reset();},onKeyDown:function(e,keyCode){TVA.log('keydown in '+this.name);if(this.listenKeys&&Model.App.listen){switch(keyCode){case Keys.getBind('Back'):break;case Keys.getBind('Up'):this.navUpElement(e);break;case Keys.getBind('Down'):this.navDownElement(e);break;case Keys.getBind('Left'):this.navLeftElement(e);break;case Keys.getBind('Right'):this.navRightElement(e);break;case Keys.getBind('Enter'):$('#'+TVA.onFocus).click();e.stopPropagation();break;case Keys.getBind('Cross'):$('#'+TVA.onFocus).click();e.stopPropagation();break;}
this.keydownCB&&this.keydownCB(e,keyCode);}
if(this.scrolling){e.stopPropagation();}},_navigate:function(direction,e){this.previousChild=this.activeChild;var nextChild=this.navigation[this.activeChild][direction];if(nextChild&&this.children[nextChild]){this.noSibling=false;this.children[nextChild].view.enable();e.stopPropagation();e.stopImmediatePropagation();}else if($(this.rootID).find('#'+nextChild).length){this.noSibling=false;TVA.setFocus(nextChild);this.activeChild=nextChild;this.activateParent();nextChild=this.navigation[this.activeChild][direction];if(nextChild){nextChild=nextChild.replace('_Overlay','');if(!document.getElementById(nextChild)&&this.hiddenElements[nextChild]){}}
e.stopPropagation();e.stopImmediatePropagation();this.gridNavCallBack&&this.gridNavCallBack();}else{this.noSibling=true;}},activateParent:function(){$('.gridElement').removeClass('active');$('#'+this.activeChild.replace('_Overlay','')).addClass('active');ViewControllerManager.ViewControllers[this.name].parentVC.activeChild=this.name;},adjustSiblings:function(element){var left=parseInt(document.getElementById(element.replace('_Overlay','')).style.left.replace('px',''));var width=parseInt(document.getElementById(element).style.width.replace('px',''));var padding=this.horizontalMargin;var index=parseInt(element.split('_pos_')[1].split('_')[0]);var i=index-1;if(i<0){i=this.columns-1;}
var id='Grid'+this.cloneIndex+'_row_0_Item_pos_'+i;var l=left-width-padding;document.getElementById(id).style.left=l+'px';i=index+1;if(i>this.columns-1){i=0;}
id='Grid'+this.cloneIndex+'_row_0_Item_pos_'+i;l=left+width+padding;document.getElementById(id).style.left=l+'px';},_targetItem:function(e,direction){var targetChild=this.navigation[this.activeChild][direction];if(targetChild){if(this.infinite){if(direction!=='Down'){var el=targetChild.replace('_Overlay','');var padding=this.horizontalMargin;if(!$('#'+targetChild)[0]){var s=targetChild.split('row_')[1].split('_Item');var row=parseInt(s[0]);this.pushOnScreen(el,row);}
var width=parseInt(document.getElementById(el).style.width.replace('px',''));var left=parseInt(document.getElementById(this.activeChild.replace('_Overlay','')).style.left.replace('px',''));if(direction==='Left'){left=left-width-padding;}else if(direction==='Right'){left=left+width+padding;}
document.getElementById(el).style.left=left+'px';this.adjustSiblings(el);var grid=el.slice(0,5);if(grid==='Grid2'){var aux=el.replace('Grid2_row_0_Item_pos_','');aux=parseInt(aux);$('#featuredCounter').find('.featuredCounterBlock').removeClass('active');$('#featuredCounter').find('.featuredCounterBlock:nth-child('+(aux+1)+')').addClass('active');}}}
if(this.isElementObscured(targetChild,true,direction)){}
this._navigate(direction,e);this._setGridIndex(targetChild);}else{this.noSibling=true;}
this.toggleArrows();},mouseOut:function(e){this.mouseOutCB&&this.mouseOutCB(e);this.parentListMouseOutCB&&this.parentListMouseOutCB(e);},hideArrows:function(e){if(e.relatedTarget&&e.relatedTarget.className!=='Grid_Container'&&e.relatedTarget.className!=='Grid'&&e.relatedTarget.className.indexOf('Arrow')<0){$(this.rootID+' > .Arrow').hide();}},setArrows:function(){var actionWidth=parseInt($(this.rootID+' .action').css('width').replace('px',''));var actionHeight=parseInt($(this.rootID+' .action').css('height').replace('px',''));var actionTop=parseInt($(this.rootID+' .action').css('top').replace('px',''));var actionLeft=parseInt($(this.rootID+' .action').css('left').replace('px',''));var arrowWidth=parseInt($(this.rootID+' .Left_Arrow').css('width').replace('px',''));var arrowHeight=parseInt($(this.rootID+' .Left_Arrow').css('height').replace('px',''));var top=((actionHeight/2)-(arrowHeight/2))+actionTop;var left=actionLeft-arrowWidth;$(this.rootID+' .Left_Arrow').css({top:top+'px',left:'0px'});arrowWidth=parseInt($(this.rootID+' .Right_Arrow').css('width').replace('px',''));arrowHeight=parseInt($(this.rootID+' .Right_Arrow').css('height').replace('px',''));top=((actionHeight/2)-(arrowHeight/2))+actionTop;left=actionWidth+actionLeft;$(this.rootID+' .Right_Arrow').css({top:top+'px',right:'0px'});arrowWidth=parseInt($(this.rootID+' .Up_Arrow').css('width').replace('px',''));arrowHeight=parseInt($(this.rootID+' .Up_Arrow').css('height').replace('px',''));top=actionTop-arrowHeight;left=((actionWidth/2)-(arrowWidth/2))+actionLeft;$(this.rootID+' .Up_Arrow').css({top:top+'px',left:left+'px'});arrowWidth=parseInt($(this.rootID+' .Down_Arrow').css('width').replace('px',''));arrowHeight=parseInt($(this.rootID+' .Down_Arrow').css('height').replace('px',''));top=actionHeight+actionTop;left=((actionWidth/2)-(arrowWidth/2))+actionLeft;$(this.rootID+' .Down_Arrow').css({top:'615px',left:left+'px'});$(this.rootID+' .Left_Arrow').hide();$(this.rootID+' .Right_Arrow').hide();$(this.rootID+' .Up_Arrow').hide();$(this.rootID+' .Down_Arrow').hide();},toggleArrows:function(){if(this.showArrows){if(this.orientation==='horizontal'){if(this.rootID==='#home_featured'){if(this.scrollHorizontalIndex<=this.size){$(this.rootID+' > .Right_Arrow').show();}else{$(this.rootID+' > .Right_Arrow').hide();}
if(this.scrollHorizontalIndex>=0){$(this.rootID+' > .Left_Arrow').show();}else{$(this.rootID+' > .Left_Arrow').hide();}}else if(this.rootID==='#home_red_carpet'){if(this.scrollHorizontalIndex<this.size-1){$(this.rootID+' > .Right_Arrow').show();}else{$(this.rootID+' > .Right_Arrow').hide();}
if(this.scrollHorizontalIndex>0){$(this.rootID+' > .Left_Arrow').show();}else{$(this.rootID+' > .Left_Arrow').hide();}}else if(this.rootID==='#home_now_showing'||this.rootID==='#home_upcoming'||this.rootID==='#myMovies_active_film'||this.rootID==='#myMovies_reminders'||this.rootID==='#myMovies_past_films'){if(this.scrollHorizontalIndex<(this.size-5)){$(this.rootID+' > .Right_Arrow').show();}else{$(this.rootID+' > .Right_Arrow').hide();}
if(this.scrollHorizontalIndex>0){$(this.rootID+' > .Left_Arrow').show();}else{$(this.rootID+' > .Left_Arrow').hide();}}else if(this.rootID==='#details_media'){if(this.scrollHorizontalIndex<(this.size-2)){$(this.rootID+' > .Right_Arrow').show();}else{$(this.rootID+' > .Right_Arrow').hide();}
if(this.scrollHorizontalIndex>0){$(this.rootID+' > .Left_Arrow').show();}else{$(this.rootID+' > .Left_Arrow').hide();}}else if(this.rootID==='#media_player_thumbs'){$(this.rootID+' > .Right_Arrow').hide();$(this.rootID+' > .Left_Arrow').hide();}
$(this.rootID+' > .Down_Arrow').hide();$(this.rootID+' > .Up_Arrow').hide();}else if(this.orientation==='vertical'){if(this.row<this.rows-1){$(this.rootID+' > .Down_Arrow').show();}else{$(this.rootID+' > .Down_Arrow').hide();}
if(this.row>0&&this.scrollVerticalIndex!=0){$(this.rootID+' > .Up_Arrow').show();}else{$(this.rootID+' > .Up_Arrow').hide();}
$(this.rootID+' > .Left_Arrow').hide();$(this.rootID+' > .Right_Arrow').hide();}
}else{$(this.rootID+' > .Right_Arrow').hide();$(this.rootID+' > .Left_Arrow').hide();$(this.rootID+' > .Down_Arrow').hide();$(this.rootID+' > .Up_Arrow').hide();}},navLeftElement:function(e){if(e.type==='click'){this.hover=true;}
TVA.log('navLeftElement in '+this.name);if(this.listenKeys){this._targetItem(e,'Left');}else{e.stopPropagation();}},navRightElement:function(e){if(e.type==='click'){this.hover=true;}
TVA.log('navRightElement in '+this.name);if(this.listenKeys){this._targetItem(e,'Right');}else{e.stopPropagation();}},navUpElement:function(e){if(e.type==='click'){this.hover=true;}
if(this.listenKeys){this._targetItem(e,'Up');}else{e.stopPropagation();}},navDownElement:function(e){if(e.type==='click'){this.hover=true;}
if(this.listenKeys){this._targetItem(e,'Down');}else{e.stopPropagation();}},updateGrid:function(){this.hiddenElements={};var maxCarouselElements=this.size;var cellCount=0;$(this.rootID+' .Grid_Container').html('');for(var i=0;i<this.rows;i++)
{var row='';if($(this.rootID+' .Grid_Container').find('#Grid'+this.cloneIndex+'_row_'+i).length){row='Grid'+this.cloneIndex+'_row_'+i;}else{row='Grid'+this.cloneIndex+'_row_'+i;var inlineStyle='style="position:absolute;width:100px;height:'+this.cellDims.height+'px"';$(this.rootID+' .Grid_Container').append('<div id="'+row+'" class="gridRow" '+inlineStyle+'></div>');}
var maxHeight=0;for(var j=0;j<this.columns;j++)
{var elementId=row+'_Item_pos_'+j;if(this.contents[cellCount]){var content=this.contents[cellCount].content||'';if($(this.rootID+' .Grid_Container #'+row+' #'+elementId)[0]){$(this.rootID+' .Grid_Container #'+row+' #'+elementId+' .content').html(content);}else
{var inlineStyle='position:absolute;';var cellWidth=this.cellDims.width>0?'width:'+this.cellDims.width+'px;':'';var cellHeight=this.cellDims.height>0?'height:'+this.cellDims.height+'px;':'';inlineStyle+=cellWidth;inlineStyle+=cellHeight;var el=document.createElement('DIV');el.setAttribute('id',elementId);el.setAttribute('class','gridElement');el.setAttribute('style',inlineStyle);var elContent=document.createElement('DIV');elContent.setAttribute('class','content');elContent.setAttribute('style','position:absolute;');elContent.innerHTML=content;var elOverlay=document.createElement('DIV');elOverlay.setAttribute('id',elementId+'_Overlay');elOverlay.setAttribute('class','Grid_Item_Overlay hoveritem');elOverlay.setAttribute('style','position:absolute;width:100%;height:100%;');el.appendChild(elContent);el.appendChild(elOverlay);if(this.performance){if(!document.getElementById(this.name))
debugger;var rootEl=document.getElementById(this.name).children[0];var rootX=parseInt(rootEl.style.left.replace('px','')||0);var containerX=parseInt(rootEl.children[0].children[0].style.left.replace('px',''));var width=parseInt(el.style.width.replace('px',''));var elementX=j*width;if(rootX+containerX+elementX>1280||(rootX+containerX+elementX)+width<0){el.style.left=elementX+'px';this.hiddenElements[elementId]=el;this.adjustElement(row,el,elementId,j);}else{document.getElementById(row).appendChild(el);this.adjustElement(row,el,elementId,j);}}else{document.getElementById(row).appendChild(el);this.adjustElement(row,el,elementId,j);}}}
cellCount++;}
var y=0;if(i>0){var rowID='Grid'+this.cloneIndex+'_row_'+(i-1);var top=$(this.rootID+' .Grid_Container #'+rowID).position().top;y=top+$(this.rootID+' .Grid_Container #'+rowID).height()+this.verticalMargin;}else{y=0;}
if($(this.rootID+' .Grid_Container #'+row).position().top===0){$(this.rootID+' .Grid_Container #'+row).css({top:y});}
var rowEls=$(this.rootID+' .Grid_Container .gridRow');var totalGridHeight=0;for(var rowIndex=0;rowIndex<rowEls.length;rowIndex++){totalGridHeight+=$(rowEls[rowIndex]).height();}
$(this.rootID+' .Grid_Container').css({height:totalGridHeight});}
this.toggleArrows();},adjustElement:function(row,el,elementId,j){if(this.autoSizeRows){var height=$(el.children[0]).css('height');height=parseInt(height.replace('px',''));el.style.height=(height+this.cellDims.height)+'px';document.getElementById(row).style.height=(height+this.cellDims.height)+'px';var top=(parseInt(el.style.height.replace('px',''))/2)-(height/2);el.children[0].style.top=top+'px';}else{el.children[0].style.width='100%';el.children[0].style.height='100%';}
var width=(parseInt(el.style.width.replace('px',''))+this.horizontalMargin)*j;el.style.left=width+'px';},onButtonOut:function(e){$(this.rootID+' > .hoverButton').removeClass('active');e.stopPropagation();},onButtonHover:function(e){$(this.rootID+' > .'+e.target.classList[0]).addClass('active');e.stopPropagation();},onHover:function(event){if(event.target.classList.contains('hoveritem')&&!this._isWithinViewport(event.target)){event.stopImmediatePropagation();}
else{var direction=this._getDirection(event.target.id);this.hover=true;this._setGridIndex(event.target.id);this.toggleArrows();this._enableElement(event.target.id);this.hoverCB&&this.hoverCB(event,direction);this.parentListHoverCB&&this.parentListHoverCB(event,direction,true);event.stopPropagation();}},_setGridIndex:function(id){if($('#'+id).length){var element=id;element=element.split('_Item_pos_');var row=element[0];var column=element[1];row=row.replace('Grid'+this.cloneIndex+'_row_','');column=column.replace('_Overlay','');this.pos=parseInt(column);this.row=parseInt(row);}},clickEvent:function(){},scrollLeft:function(scrollAmount){this.scroll(-1,scrollAmount,'horizontal');if(this.scrollHorizontalIndex===this.size-1){this.scrollHorizontalIndex=0;}
else if(this.scrollHorizontalIndex<this.size-1)
this.scrollHorizontalIndex++;},scrollRight:function(scrollAmount){this.scroll(1,scrollAmount,'horizontal');if(this.scrollHorizontalIndex===0){this.scrollHorizontalIndex=this.size-1;}
else if(this.scrollHorizontalIndex>0)
this.scrollHorizontalIndex--;},scrollUp:function(scrollAmount){this.scroll(-1,scrollAmount,'vertical');if(this.scrollVerticalIndex<this.rows){this.scrollVerticalIndex++;}},scrollDown:function(scrollAmount){this.scroll(1,scrollAmount,'vertical');if(this.scrollVerticalIndex>0){this.scrollVerticalIndex--;}},scroll:function(direction,distance,orientation){this.listenKeys=false;this.scrolling=true;var scope=this;var newPos='0px';var animCSS={};if(orientation==='vertical'){var y=$(this.rootID+' .Grid_Container').position().top;var dy=(distance||53)*direction;var clipY=$(this.rootID+' .clip').position().top;var newPos=Math.round(dy+y);this.containerPos.y=newPos;this.newPos=newPos+'px';animCSS={top:this.newPos};this._animComplete({top:this.containerPos.y,direction:this.directions[orientation][direction]});}else if(orientation==='horizontal'){var x=$(this.rootID+' .Grid_Container').position().left;var dx=(distance||53)*direction;this.newPos=Math.round((dx+x))+'px';animCSS={'left':this.newPos};this.containerPos.x=Math.round(dx+x);this._animComplete({left:this.containerPos.x,direction:this.directions[orientation][direction]});}
$(this.rootID+' .Grid_Container').css(animCSS);if(this.performance){this.cleanOffScreen(this.directions[orientation][direction]);}},_animComplete:function(params){var interval=80;clearTimeout(this.animCompleteInterval);var scope=this;if(typeof params.left==='number'){if(Math.round($(this.rootID+' .Grid_Container').position().left)===Math.round(params.left)){this.listenKeys=true;this.scrolling=false;if(this.performance){}}else{this.animCompleteInterval=setTimeout(function(){scope._animComplete(params);},interval);}}else if(typeof params.top==='number'){if(Math.round($(this.rootID+' .Grid_Container').position().top)===Math.round(params.top)){this.listenKeys=true;this.scrolling=false;if(this.performance){}}else{this.animCompleteInterval=setTimeout(function(){scope._animComplete(params);},interval);}}},cleanOffScreen:function(direction){if(direction==='Right'){var findOffScreen=true;for(var i=this.pos;i<this.columns&&findOffScreen;i++){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(!document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.pushOnScreen(el,j);}}}
findOffScreen=true;for(var i=this.pos;i>=0&&findOffScreen;i--){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(this.isOffscreen(element)&&document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){var el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.popOffScreen(el,j);}}}}else if(direction==='Left'){var findOffScreen=true;for(var i=this.pos;i>=0&&findOffScreen;i--){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(!document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.pushOnScreen(el,j);}}}
findOffScreen=true;for(var i=this.pos;i<this.columns&&findOffScreen;i++){var element='Grid'+this.cloneIndex+'_row_'+this.row+'_Item_pos_'+i;if(this.isOffscreen(element)&&document.getElementById(element)){findOffScreen=false;for(var j=0;j<this.rows;j++){var el='Grid'+this.cloneIndex+'_row_'+j+'_Item_pos_'+i;this.popOffScreen(el,j);}}}}else if(direction==='Up'){var findOffScreen=true;for(var i=this.offset;i>=0&&findOffScreen;i--){var element='Grid'+this.cloneIndex+'_row_'+i;if(!document.getElementById(element)){findOffScreen=false;this.pushRowOnScreen(element);}}
findOffScreen=true;for(var i=this.offset;i<this.rows&&findOffScreen;i++){var element='Grid'+this.cloneIndex+'_row_'+i;if(document.getElementById(element)&&this.isDOMElementOffScreen(element)){this.popRowOffScreen(element);}}}else if(direction==='Down'){var findOffScreen=true;for(var i=this.offset;i<this.rows&&findOffScreen;i++){var element='Grid'+this.cloneIndex+'_row_'+i;if(!document.getElementById(element)){findOffScreen=false;this.pushRowOnScreen(element);}}
findOffScreen=true;for(var i=this.offset;i>=0&&findOffScreen;i--){var element='Grid'+this.cloneIndex+'_row_'+i;if(document.getElementById(element)&&this.isDOMElementOffScreen(element)){findOffScreen=false;this.popRowOffScreen(element);}}}
},scrollTo:function(row,col,direction){this.readyToSetScroll=false;var overlayElement='Grid'+this.cloneIndex+'_row_'+row+'_Item_pos_'+col+'_Overlay';this.row=row;this.pos=col;this.isElementObscured(overlayElement,true,direction);this.activeChild=overlayElement;TVA.setFocus(this.activeChild);this.activateParent();},isElementObscured:function(overlayElement,autoScroll,direction){var id=overlayElement.replace('_Overlay','');var rootEl=document.getElementById(this.name);var element=null;if(document.getElementById(id)){element=document.getElementById(id);overlayElement=document.getElementById(overlayElement);}else if(this.hiddenElements[id]){element=this.hiddenElements[id];overlayElement=element.children[1];}
var container=rootEl.children[0].children[0].children[0];if((direction==='Left'||direction==='Right')&&this.orientation==='horizontal'){var matrixLeft=$(this.rootID+' .Grid_Container').position().left;var actionZoneWidth=rootEl.children[0].style.width.replace('px','');matrixLeft=container.style.left.replace('px','');matrixLeft=parseInt(matrixLeft===''?0:matrixLeft);var pos={left:element.style.left.replace('px',''),top:element.style.top.replace('px','')};var width=$(overlayElement).width();var scrollAmount=0;var scroll=autoScroll||true;var x=parseInt(pos.left)+matrixLeft;if(x<(0+this.screenPadding)){if(scroll){var dX=Math.abs(x)+this.screenPadding;this.scrollRight(dX);}
return true;}else if((x+width)>(0+actionZoneWidth)-this.screenPadding){scrollAmount=(x+width)-(actionZoneWidth-this.screenPadding);if(scroll){this.scrollLeft(scrollAmount);}
return true;}else{return false;}}else if((direction==='Up'||direction==='Down')&&this.orientation==='vertical'){var matrixTop=$(this.rootID+' .Grid_Container').position().top;var actionZoneHeight=parseInt(rootEl.children[0].style.height.replace('px',''));matrixTop=container.style.top.replace('px','');matrixTop=parseInt(matrixTop===''?0:matrixTop);var pos=$(overlayElement).parent().parent().position();var height=$(overlayElement).height();var scrollAmount=0;var scroll=autoScroll||true;var y=pos.top+matrixTop;if(y<0)
{if(scroll){var dY=Math.abs(y)+this.screenPadding;this.scrollDown(dY);this.offset--;}
return true;}else if((y+height)>(actionZoneHeight)-this.screenPadding)
{scrollAmount=(y+height)-(actionZoneHeight-this.screenPadding);if(scroll){this.scrollUp(scrollAmount);this.offset++;}
return true;}else{return false;}}},hideAllOffscreen:function(){var noRows=document.getElementById(this.name).children[0].children[0].children[0].children.length;var noCols=document.getElementById(this.name).children[0].children[0].children[0].children[0].children.length;for(var i=0;i<noRows;i++){for(var j=0;j<noCols;j++){var elId='Grid'+this.cloneIndex+'_row_'+i+'_Item_pos_'+j;if(this.isOffscreen(elId)){this.popOffScreen(elId,i);}}}},hideAllRowsOffscreen:function(){for(var i=0;i<this.rows;i++){var element='Grid'+this.cloneIndex+'_row_'+i;if(document.getElementById(element)&&this.isDOMElementOffScreen(element)){this.popRowOffScreen(element);}}},pushOnScreen:function(element,row){if(document.getElementById(element)){element=document.getElementById(element);}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
document.getElementById(this.name).children[0].children[0].children[0].children[row].appendChild(element);},pushRowOnScreen:function(element){if(document.getElementById(element)){element=document.getElementById(element);}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
document.getElementById(this.name).children[0].children[0].children[0].appendChild(element);},popOffScreen:function(element,row){if(document.getElementById(element)){this.hiddenElements[element]=document.getElementById(element);element=this.hiddenElements[element];}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
document.getElementById(this.name).children[0].children[0].children[0].children[row].removeChild(element);},popRowOffScreen:function(element){if(document.getElementById(element)){this.hiddenElements[element]=document.getElementById(element);element=this.hiddenElements[element];}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
document.getElementById(this.name).children[0].children[0].children[0].removeChild(element);},isOffscreen:function(element){var offScreen=true;var left,rootX,elementX,containerX,width,margin;var rootEl=document.getElementById(this.name).children[0];if(document.getElementById(element)){element=document.getElementById(element);}else if(this.hiddenElements[element]){element=this.hiddenElements[element];}
left=element.style?element.style.left.replace('px',''):0;left=left===''?0:left;rootX=parseInt(rootEl.style?rootEl.style.left.replace('px',''):0);elementX=parseInt(left);containerX=parseInt(rootEl.children[0].children[0].style.left.replace('px',''));width=parseInt(element.style?element.style.width.replace('px',''):0);return rootX+containerX+elementX>1280||(rootX+containerX+elementX)+width<0;},isDOMElementOffScreen:function(elementId){var offScreen=false;var el=document.getElementById(elementId);var elRect=el.getClientRects()[0];var width=elRect.width;var height=elRect.height;var elX=elRect.left;var elY=elRect.top;if(elX>=1280||elX+width<=0){return true;}
if(elY>=720||elY+height<=0){return true;}
return offScreen;},_getDirection:function(elementId){elementId=elementId.split('_Item_pos_');var row=elementId[0];var column=elementId[1];row=row.replace('Grid'+this.cloneIndex+'_row_','');column=column.replace('_Overlay','');if(parseInt(row)>this.row){return'Down';}else if(parseInt(row)<this.row){return'Up';}else if(parseInt(column)<this.pos){return'Left';}else if(parseInt(column)>this.pos){return'Right';}},onClick:function(e){if(e.target.classList.contains('hoveritem')&&!this._isWithinViewport(e.target)){e.stopImmediatePropagation();}else{this.clickCB&&this.clickCB(e);e.stopPropagation();}},_isWithinViewport:function(el){var top=el.offsetTop;var left=el.offsetLeft;var width=el.offsetWidth;var height=el.offsetHeight;while(el.offsetParent){el=el.offsetParent;top+=el.offsetTop;left+=el.offsetLeft;}
return(top>=window.pageYOffset&&left>=window.pageXOffset&&(top+height)<=(window.pageYOffset+720)&&(left+width)<=(window.pageXOffset+1280));},reset:function(){$(this.rootID+' .Grid_Container').html('');},gridNavCallBack:function(){}}));})();