var VideoController=(function(){var Video=Class.create({init:function(){this.videoSizes={home:{width:480,height:270,x:622,y:224},full:{width:1280,height:720,x:0,y:0},none:{width:0,height:0,x:0,y:0}};this.size=null;this.stopped=false;this.playing=false;this.paused=false;this.connecting=false;this.buffering=false;this.finished=false;this.error=false;this.previousState=null;this.currentSeconds=0;this.url=null;this.throbber={home:{x:624,y:425},full:{x:624,y:443},details:{x:327,y:333}};this.player=ViewControllerManager.find("Player");this.previousBufferProgress=0;TVA_Player.init();TVA_Player.readyVideo();$("#videoThrobber").css({top:this.throbber.home.y,left:this.throbber.home.x});var self=this;playStateChanged=function(state){switch(state){case 0:self.stopped=true;self.playing=false;self.paused=false;self.connecting=false;self.buffering=false;self.finished=false;self.error=false;TVA.log("STREAM STOPPED !");break;case 1:self.stopped=false;self.playing=true;self.paused=false;self.connecting=false;self.buffering=false;self.finished=false;self.error=false;TVA.log("STREAM PLAYING !");break;case 2:self.stopped=false;self.playing=false;self.paused=true;self.connecting=false;self.buffering=false;self.finished=false;self.error=false;TVA.log("STREAM PAUSED !");break;case 3:self.stopped=false;self.playing=false;self.paused=false;self.connecting=true;self.buffering=false;self.finished=false;self.error=false;TVA.log("STREAM CONNECTING !");break;case 4:self.stopped=false;self.playing=false;self.paused=false;self.connecting=false;self.buffering=true;self.finished=false;self.error=false;TVA.log("STREAM BUFFERING !");break;case 5:self.stopped=false;self.playing=false;self.paused=false;self.connecting=false;self.buffering=false;self.finished=true;self.error=false;TVA.log("STREAM FINISHED !");break;case 6:self.stopped=false;self.playing=false;self.paused=false;self.connecting=false;self.buffering=false;self.finished=false;self.error=true;TVA.log("STREAM ERROR !");break;}
TVA.log("PreviousState - "+self.previousState);self.previousState=state;TVA.log("CurrentState - "+state);self.player.stateChange(state);};playError=function(error){TVA.log(error);self.player._resetPlayer();};bufferingProgress=function(bufferProgress){if(settings.device!=="samsung_tizen"&&settings.device!=="panasonic"){if(bufferProgress>100&&self.previousBufferProgress===0){bufferProgress=0;}
else if((bufferProgress>100&&self.previousBufferProgress>0)){bufferProgress=100;}
else if((bufferProgress>100&&self.previousBufferProgress===100)||(bufferProgress<self.previousBufferProgress)){bufferProgress=self.previousBufferProgress;}
else if(bufferProgress<100){bufferProgress=Math.floor(bufferProgress);}
self.previousBufferProgress=bufferProgress;TVA.log("BUFFER PROGRESS - "+bufferProgress);self.player.genericBar("#buffer",bufferProgress);}};playHeadChanged=function(seconds){Util.hideSpriteLoader();if(TVA.device==="firetv"){if(TVA.onHUD){self.stop();return;}}
if(!TVA_Player.active){self.stop();return;}
self.currentSeconds=parseInt(seconds);self.player.playHead(seconds);};},fullscreen:function(){this.size="full";this._changeSize(this.videoSizes.full);},getLength:function(){var length=TVA_Player.getLength();if(length===Infinity)length=0;return length;},getCurrentTime:function(){return TVA_Player.getCurrentTime();},getState:function(){return TVA_Player.getState();},setURL:function(url){this.url=url;TVA_Player.setURL(url);},play:function(seektime){var playObj={};if(seektime){playObj["startTime"]=seektime;}
if(settings.device==="googletv"||settings.device==="androidtv"||settings.device==="operatv"){setTimeout(function(){TVA_Player.play(playObj);},1000);}else{TVA_Player.play(playObj);}},pause:function(){return TVA_Player.pause(true);},resume:function(){TVA_Player.pause(false);},stop:function(){TVA_Player.stop();},forward:function(seconds){TVA_Player.forward(seconds||10);},backward:function(seconds){TVA_Player.backward(seconds||10);},showPlayer:function(){TVA_Player.show();},showQmenu:function(){TVA_Player.showQMenu();},hidePlayer:function(){this.previousBufferProgress=0;TVA_Player.hide();},_changeSize:function(sizeof){if(settings.device!=="ps3"&&settings.device!=="ps4"&&settings.device!=="psvita")
{TVA_Player.setXY(sizeof.x,sizeof.y);TVA_Player.setWidth(sizeof.width);TVA_Player.setHeight(sizeof.height);}else{TVA_Player.setXY(sizeof.x,sizeof.y);setTimeout(function(){TVA_Player.setWidth(sizeof.width);},1000);setTimeout(function(){TVA_Player.setHeight(sizeof.height);},1000);}
Model.App.playerX=sizeof.x;Model.App.playerY=sizeof.y;},_updateThrobber:function(){$("#videoThrobber").css({top:this.throbber[this.size].y,left:this.throbber[this.size].x});}});return new Video();})();