(function(){"use strict";var base=ViewControllerManager.findClass("ViewControllerNav");ViewControllerManager.newClassDef("VCarouselVC",Class.create({_extends_:base,_init_:function(args){base.call(this,args);this.activeChild='V_Carousel_Item_pos_0_Overlay';this.navigation={};this.pos=0;this.size=0;this.maxEl=3;this.activePos=0;this.offset=0;this.images=[];this.text=[];this.contents=[];},init:function(params){this.offset=0;this.pos=0;this.activeChild='V_Carousel_Item_pos_0_Overlay';this.contents=params.contents||[];this.size=params.contents.length;this.maxEl=this.size<params.length&&this.size!=0?this.size:params.length;for(var i=0;i<this.maxEl;i++){if(i===0)
{if(this.size>1){this.navigation['V_Carousel_Item_pos_'+i+'_Overlay']={Down:'V_Carousel_Item_pos_'+(i+1)+'_Overlay'};}else{this.navigation['V_Carousel_Item_pos_'+i+'_Overlay']={};}}else if(i===this.maxEl-1&&i!=0)
{this.navigation['V_Carousel_Item_pos_'+i+'_Overlay']={Up:'V_Carousel_Item_pos_'+(i-1)+'_Overlay',Down:'V_Carousel_Item_pos_'+i+'_Overlay'};}else{var nav={Up:'V_Carousel_Item_pos_'+(i-1)+'_Overlay',Down:'V_Carousel_Item_pos_'+(i+1)+'_Overlay'};this.navigation['V_Carousel_Item_pos_'+i+'_Overlay']=nav;}}},onUnload:function(){this.pos=0;this.images=[];this.text=[];this.contents=[];TVA.offFocus(this.activeChild);},onLoad:function(){this._loadVC();this.images=[];this.text=[];this.pos=0;this.activeChild='V_Carousel_Item_pos_0_Overlay';this.clickEvent=null;},_loadVC:function(){},render:function(location){this._super(location);$('.Carousel_Item_Overlay').removeClass('focus');if(settings.device==='philips'||settings.device==='lg'||settings.device==='foxxum'){if(ViewControllerManager.find("Root").activeChild==='SetLocation'||ViewControllerManager.find("Root").activeChild==='SetFavoriteLocation'){}else{this.enable();}}else{this.enable();}
$(this.rootID+' .carouselElement p').html('');$(this.rootID+' .carouselElement').css('background-image','url()');this.updateCarousel();this.activateParent();},onKeyDown:function(e,keyCode){TVA.log('keydown in V Carousel');$('.V_Carousel.Arrow').removeClass('arrowHover');if(Model.App.listen){switch(keyCode){case Keys.getBind("Back"):break;case Keys.getBind("Up"):this.navUpElement(e);break;case Keys.getBind("Down"):this.navDownElement(e);break;case Keys.getBind("Left"):this._navigate('Left',e);break;case Keys.getBind("Right"):this._navigate('Right',e);break;case Keys.getBind("Enter"):$('#'+TVA.onFocus).click();e.stopPropagation();break;case Keys.getBind("Cross"):$('#'+TVA.onFocus).click();e.stopPropagation();break;}}},_navigate:function(direction,e){var nextChild=this.navigation[this.activeChild][direction];if(nextChild&&this.children[nextChild]){this.children[nextChild].view.enable();e.stopPropagation();}else if($(this.rootID).find('#'+nextChild).length){TVA.setFocus(nextChild);this.activeChild=nextChild;this.activateParent();e.stopPropagation();this.navCallBack&&this.navCallBack();}},activateParent:function(){$('.carouselElement').removeClass('active');$('#'+this.activeChild.replace('_Overlay','')).addClass('active');},_prevItem:function(e){var prevChild=this.navigation[this.activeChild]["Up"];if(this.pos>0){this.pos--;}
$('#Top_Arrow').addClass('arrowHover');if(this.pos-(this.offset*this.maxEl)<0){this.offset--;this.updateCarousel();}else{this._navigate("Up",e);}},_nextItem:function(e){var nextChild=this.navigation[this.activeChild]["Down"];if(this.pos<this.size){this.pos++;}
$('#Bottom_Arrow').addClass('arrowHover');if(this.pos<this.size-1&&this.pos===this.maxEl){this.offset++;this.updateCarousel();}else{this._navigate("Down",e);}},navUpElement:function(e){if(this.pos>0){this._prevItem(e);e.stopPropagation();}},navDownElement:function(e){if(this.pos<this.size-1){this._nextItem(e);e.stopPropagation();}else{this._navigate("Down",e);}},updateCarousel:function(){var maxCarouselElements=this.maxEl;$(this.rootID+' .carouselElement').hide();for(var i=0;i<maxCarouselElements;i++){var index=i+this.offset;$(this.rootID+' #V_Carousel_Item_pos_'+i).hide();$(this.rootID+' #V_Carousel_Item_pos_'+i+' div').html('');if(this.contents[index]){if(index<this.contents.length-1&&this.contents.length>3){$('#Bottom_Arrow').show();}else{$('#Bottom_Arrow').hide();}
if(index>2){$('#Top_Arrow').show();}else{$('#Top_Arrow').hide();}
$(this.rootID+' #V_Carousel_Item_pos_'+i).show();var url=this.contents[index].images||'';var bgcss=this.contents[index].bgcss||{};var text=this.contents[index].text||'';if(!$(this.rootID+' #V_Carousel_Item_pos_'+i)[0]){var newElement='<li id="V_Carousel_Item_pos_'+i+'" class="carouselElement"><div class="content"></div><div id="V_Carousel_Item_pos_'+i+'_Overlay" class="Carousel_Item_Overlay hoveritem"></div></li>';$(this.rootID+' ul').append(newElement);}
if(bgcss!={}){$(this.rootID+' #V_Carousel_Item_pos_'+i).css(bgcss);}
if(url!=''){$(this.rootID+' #V_Carousel_Item_pos_'+i).css('background-image','url('+url+')');}
if($(this.rootID+' #V_Carousel_Item_pos_'+i+' div.content')[0]){$(this.rootID+' #V_Carousel_Item_pos_'+i+' div.content').html(text);}else{$(this.rootID+' #V_Carousel_Item_pos_'+i+' div.content').html(text);}}}},onHover:function(event){$('#TextScroller').removeClass('active');$('.Arrow').removeClass('arrowHover');if($('#'+event.target.id).hasClass('Arrow')){$('#'+event.target.id).addClass('arrowHover');}else{var element=event.target.id;element=element.replace('_Overlay','');var i=element[element.length-1];this._setCarouselIndex(parseInt(i));this._enableElement(event.target.id);}
if(typeof this.hoverCallback==='function'){this.hoverCallback(event.target.id);}
event.stopPropagation();},_setCarouselIndex:function(index){this.pos=this.offset+index;},clickEvent:function(){},navCallBack:function(){},arrowUp:function(e){this.navUpElement(e);},arrowDown:function(e){this.navDownElement(e);},hoverCallback:null}));})();